{{- if .Values.app.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "laravel-chart.fullname" . }}
  labels:
    {{- include "laravel-chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.app.persistence.size }}
  selector:
    matchLabels:
      {{- include "laravel-chart.selectorLabels" . | nindent 6 }}
{{- end }}
